// This needs to be generated using codegen

#include <string>
#include <unordered_map>

#include "ReactSkia/utils/RnsLog.h"

#include "RSkThirdPartyNativeModuleProvider.h"

namespace facebook {
namespace react {

using namespace facebook::xplat;

RSkLegacyNativeModuleProviderProtocol RSkThirdparyNativeModuleCreatorClassWithName(std::string moduleName) {
  // This function and hash table must be generated by codegen with all the linked thirdparty Native modules
  static std::unordered_map<std::string, RSkLegacyNativeModuleProviderProtocol> NativeModulesClassMap = {
  };
  RNS_LOG_INFO("Look up for component : " << moduleName << " in thirdparty provider");

  auto p = NativeModulesClassMap.find(moduleName);
  if (p != NativeModulesClassMap.end()) {
    auto classFunc = p->second;
    return classFunc;
  }

  return nullptr;
}

} // namespace react
} // namespace facebook
