// This needs to be generated using codegen

#include "RSkThirdPartyFabricComponentsProvider.h"

#include <string>
#include <unordered_map>

#include "ReactSkia/utils/RnsLog.h"

namespace facebook {
namespace react {

RSkComponentProviderProtocol RSkThirdPartyFabricComponentsProvider(const char *componentName) {
  // This function and hash table must be generated by codegen with all the linked thirdparty RSkComponentProviderProtocol
  static std::unordered_map<std::string, RSkComponentProviderProtocol> fabricComponentsClassMap = {
  };

  RNS_LOG_TRACE("Look up for component : " << componentName << " in thirdparty provider");

  auto p = fabricComponentsClassMap.find(componentName);
  if (p != fabricComponentsClassMap.end()) {
    RNS_LOG_INFO("Found component : " << componentName << " in thirdparty provider");
    auto classFunc = p->second;
    return classFunc;
  }

  RNS_LOG_WARN("Could not find component : " << componentName << " in thirdparty provider");
  return nullptr;
}

} // namespace react
} // namespace facebook
