#define RNS_OS_MAJOR_VERSION 0
#define RNS_OS_MINOR_VERSION 1
#define RNS_OS_PATCH_VERSION 0
#define _STRINGIFY(x) #x
#define STRINGIFY(x) _STRINGIFY(x)

#define RNS_OS_VERSION RNS_OS_MAJOR_VERSION.RNS_OS_MINOR_VERSION.RNS_OS_PATCH_VERSION
