/* React Native version*/
#define RN_MAJOR_VERSION 0
#define RN_MINOR_VERSION 71
#define RN_PATCH_VERSION 0

/* React Native Skia version */
#define RNS_OS_MAJOR_VERSION 0
#define RNS_OS_MINOR_VERSION 3
#define RNS_OS_PATCH_VERSION 0
#define _STRINGIFY(x) #x
#define STRINGIFY(x) _STRINGIFY(x)

#define RNS_OS_VERSION RNS_OS_MAJOR_VERSION.RNS_OS_MINOR_VERSION.RNS_OS_PATCH_VERSION
