#!/usr/bin/python

# Copyright (C) 1994-2023 OpenTV, Inc. and Nagravision S.A.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

import sys

# Function to generate RSkThirdPartyFabricComponentsProvider.h
def generateThirdPartyFabricComponentsProviderH(buildGenPath, lookupFunctionMap):
  print('Generating RSkThirdPartyFabricComponentsProvider.Cpp...')
  TPFabricComponentHeaderTemplate = '''/**
 * This code was generated by ReactNativeSKia codegn.
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by GenerateRCTThirdPartyFabricComponentsProviderH ''' + sys.argv[0] + '''
 */

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wreturn-type-c-linkage"

#include "ReactSkia/components/RSkComponentProvider.h"

namespace facebook {
namespace react {

#ifdef __cplusplus
extern "C" {
#endif

RSkComponentProviderProtocol RSkThirdPartyFabricComponentsProvider(const char *componentName);

'''+ lookupFunctionMap +'''

#ifdef __cplusplus
}
#endif

} // namespace react
} // namespace facebook

#pragma GCC diagnostic pop'''

  cppFilePath = sys.argv[1] + '/'+'RSkThirdPartyFabricComponentsProvider.h'
  gnf= open( cppFilePath, "w+")
  gnf.write(TPFabricComponentHeaderTemplate)
  gnf.close()
# End of function generateThirdPartyFabricComponentsProviderH()
