cxx_library(
  name = 'double-conversion',

  srcs = [
    'src/bignum.cc',
    'src/bignum-dtoa.cc',
    'src/cached-powers.cc',
    'src/diy-fp.cc',
    'src/double-conversion.cc',
    'src/fast-dtoa.cc',
    'src/fixed-dtoa.cc',
    'src/strtod.cc',
  ],

  header_namespace = '',
  exported_headers = subdir_glob(
    [
      ('src', '*.h'),
    ],
    prefix = 'double-conversion',
  ),

  visibility = [ 'PUBLIC' ],
)
