
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

#include <react/renderer/components/rncore/ShadowNodes.h>

namespace facebook {
namespace react {

extern const char ActivityIndicatorViewComponentName[] = "ActivityIndicatorView";
extern const char DatePickerComponentName[] = "DatePicker";
extern const char RCTMaskedViewComponentName[] = "RCTMaskedView";
extern const char RCTProgressViewComponentName[] = "RCTProgressView";
extern const char PullToRefreshViewComponentName[] = "PullToRefreshView";
extern const char SwitchComponentName[] = "Switch";
extern const char UnimplementedNativeViewComponentName[] = "UnimplementedNativeView";

} // namespace react
} // namespace facebook
