#!/usr/bin/python

# Copyright (C) 1994-2023 OpenTV, Inc. and Nagravision S.A.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

import sys
import os

# Function to generate BUILD.gn
def generateBuildGn(externalBuildGnPath, buildTargets):
  print('Generating external/BUILD.gn...')
  buildGnTemplate = '''# External ThirdParty/Custom package builder
# This code was generated by ReactNativeSKia codegn.
#
# Do not edit this file as changes may cause incorrect behavior and will be lost
# once the code is regenerated.
#
# @generated by ''' + sys.argv[0] + '''

config("ReactSkiaExternal_config") {
  cflags_cc = [
  ]
}

source_set("external") {
  deps = [
  '''+buildTargets+'''
  ]
}'''

  if not os.path.exists(externalBuildGnPath):
    os.makedirs(externalBuildGnPath)

  buildGnPath = externalBuildGnPath + '/BUILD.gn'
  gnf= open( buildGnPath, "w+")
  gnf.write(buildGnTemplate)
  gnf.close()
# End of function generateBuildGn()
