cxx_library(
  name = 'headers_only',

  srcs = [
  ],

  header_namespace = "",
  exported_headers = subdir_glob(
    [
      ('boost', '**/*.hpp'),
    ],
    prefix = "boost",
  ),

  visibility = [ 'PUBLIC' ],
)
